# this workflow is taken from https://github.com/skaji/mi6
name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'
          - '2023.02' # fez uses "rakuast"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Upgrade zef
        run: zef upgrade --/test zef
      - name: Install Dependencies
        run: zef install --/test --deps-only .
      - name: Run Tests
        run: prove6 -I. t
